### ISSUE TITLE
Add Theme Color

### ISSUE THREAD

**Issue by andresitodeguzman** [pwa-pilipinas/hack-to-home-screen#1]
**Is your feature request related to a problem? Please describe.**
We want to add a theme color to give the app a personality.

**Describe the solution you'd like**
Add a meta tag to add a theme color of `#072540` to our web app

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by roycebradley** [comment]
@andresitodeguzman Hey, I can work on this!

**Comment by Curious-Yu** [comment]
Hello there. I tried working on this issue. But I am confused with the commit message style. Any particular way you want to name this?

**Comment by Curious-Yu** [comment]
Issue is completed. See Curious-Yu-batch3. Thank you.
