### ISSUE TITLE
UI for CRUD(Create, Read, Update, Delete) Tasks

### ISSUE THREAD

**Issue by lenmorld** [pwa-pilipinas/hack-to-home-screen#10]
**Is your feature request related to a problem? Please describe.**
There are implementations for the tasks, but they are not exposed in the UI

**Describe the solution you'd like**
Add UI to CRUD (create, read, update, delete tasks).

**Describe alternatives you've considered**
N/A

**Additional context**
For a staring point, Adding and Loading tasks would be good

I would like to take a stab at this issue as well

**Comment by lenmorld** [comment]
I can't assign it to myself, but if you think this issue is relevant, and no one is working on it, please assign this to me
Thanks

**Comment by andresitodeguzman** [comment]
Issues are broken down into smaller issues to accommodate more PRs.
