### ISSUE TITLE
Add UI/input field and handler for adding tasks

### ISSUE THREAD

**Issue by andresitodeguzman** [pwa-pilipinas/hack-to-home-screen#11]
**Is your feature request related to a problem? Please describe.**
In order to add tasks, we need to create an input field in the web app to add tasks.

**Describe the solution you'd like**
It needs to have an text field and a button that would send the content of that text area to the addTask method. Use jquery to manipulate the input field and the button. Make sure to check if input is empty or not before sending it to addTask.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dschimtz** [comment]
Hi, I'd like to contribute to this project, but I'm not exactly sure what its purpose is.
