### ISSUE TITLE
List uncompleted tasks

### ISSUE THREAD

**Issue by andresitodeguzman** [pwa-pilipinas/hack-to-home-screen#15]
**Is your feature request related to a problem? Please describe.**
We need to list the tasks we have to accomplish.

**Describe the solution you'd like**
Use getTasksList method in getting the list of uncompleted tasks. Filter the data you get to show only tasks where isDone is set to false. Use jquery to manipulate DOM. Keep it clean and minimal, prefer encapsulating code into a function.

Please make sure that the web app is still cohesive and uniform when your changes are added before opening the PR.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jcsgithub** [comment]
Hi @andresitodeguzman , I'd like to work on this issue. Hope you can assign it to me.

**Comment by abhinandansharma** [comment]
I'll send a PR soon
