### ISSUE TITLE
List completed tasks

### ISSUE THREAD

**Issue by andresitodeguzman** [pwa-pilipinas/hack-to-home-screen#16]
**Is your feature request related to a problem? Please describe.**
We need to list the tasks we have accomplished.

**Describe the solution you'd like**
Use getTasksList method in getting the list of uncompleted tasks. Filter the data you get to show only tasks where isDone is set to true. Use jquery to manipulate DOM. Keep it clean and minimal, prefer encapsulating code into a function.

Please make sure that the web app is still cohesive and uniform when your changes are added before opening the PR.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ccsCoder** [comment]
@andresitodeguzman I am interested in working on this. Could you please assign this to me ?

**Comment by andresitodeguzman** [comment]
> @andresitodeguzman I am interested in working on this. Could you please assign this to me ?

Please open a PR if you would like to take this issue. Please do note that we will prioritize the first to do the PR but would still check for code quality and appropriateness of the code changes.

**Comment by abhinandansharma** [comment]
Hey, I am working on it
