### ISSUE TITLE
Add device-width meta tags

### ISSUE THREAD

**Issue by andresitodeguzman** [pwa-pilipinas/hack-to-home-screen#2]
**Is your feature request related to a problem? Please describe.**
Make the web app mobile friendly by adding the proper meta tag.

**Describe the solution you'd like**
Add `<meta name="viewport" content="width=device-width, initial-scale=1.0">` to the head of the page.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Medha08** [comment]
Hey, @andresitodeguzman  Can I take this up?

**Comment by Curious-Yu** [comment]
Issue is completed. See Curious-Yu-batch3. Thank you.
