### ISSUE TITLE
Add ability to add tasks

### ISSUE THREAD

**Issue by andresitodeguzman** [pwa-pilipinas/hack-to-home-screen#27]
**Is your feature request related to a problem? Please describe.**
We need the ability to add tasks

**Describe the solution you'd like**
Use jquery in handling the add task input. Input should be checked, empty input is not allowed. Use Materialize toast for event messages. Use the method provided in adding the tasks, it is already in the code any you only have to call it to add the said task. Aside from adding make sure to refresh the list of uncompleted todos to reflect the added task. Use minimal, simple and straighforward logic as possible. If possible to decouple functions, you may do so.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by abhinandansharma** [comment]
Hey, Can i do this?
