### ISSUE TITLE
Add jquery

### ISSUE THREAD

**Issue by andresitodeguzman** [pwa-pilipinas/hack-to-home-screen#3]
**Is your feature request related to a problem? Please describe.**
We will use jQuery to manipulate our page. 

**Describe the solution you'd like**
1. Create an `assets` folder in the `public` folder and a `js` folder inside it if it doesn't exist yet.
2. Add the latest version of jquery min to the js folder
3. Import jquery to page. Make sure to add a defer attribute and to put it at the end of the page (below </html>/below the fold).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by hannesfant** [comment]
Mind if I go ahead and do this?
