### ISSUE TITLE
Add ability to set uncompleted task as done and done as uncompleted v.v.

### ISSUE THREAD

**Issue by andresitodeguzman** [pwa-pilipinas/hack-to-home-screen#32]
**Is your feature request related to a problem? Please describe.**
We need the ability to set a task as done and done task as uncompleted.

**Describe the solution you'd like**
In the mockup provided, both uncompleted and done task entries have a blue button on them. We will use that to set the said button to toggle the state of the task from `isDone` being set to `true` into `false` and vice versa. Use the toggleTask method/function for this one. Also, once done make sure to refresh both the uncompleted and done task list to reflect in the UI, the changes done on the task. Use an appropriate icon from [Material Design Icons](https://materialdesignicons.com/) to use in the button UI. You may either put the svg file to the assets folder and reference it to the page or insert the svg code directly.

Better if we can show a toast that would inform the user of the action. Make sure to use the components of [Materialize CSS](https://materializecss.com/).

As always make sure to keep the solution straightforward and simple. Prefer to encapsulate actions into functions/methods for reusability. The PR should still harmonize with the overall app function currently on the master branch, so make sure to test before opening the PR.

[Mockup link](https://github.com/pwa-pilipinas/hack-to-home-screen/blob/main/Frame%2017.png)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by shashwatbangar** [comment]
hey @andresitodeguzman can you assign this project to me? I would love to work on it. Also am gonna use bootstrap for styling purpose. Thank you !!
